from google import genai
from os import getenv
from dotenv import load_dotenv


load_dotenv()
api_key = getenv("GEMINI_API_KEY")

client = genai.Client(api_key=api_key)
response = client.models.generate_content(
    model="gemini-2.5-flash-lite",
    contents=
    "Extract the names of the panel below, only the people participating in the event, return the answer in a comma way easy to extract from string in python. Don't output anything but the answer"
    # "return the region of the following description. ONLY return Choose from: Africa, Brazil, China, Europe, India & South Asia, Latin America & Caribbean, Middle East, Russia, United States"
    ""
    "Covering Immigration During the Second Trump Administration Human Rights "
    "Seminar Series This panel brings together journalists from The "
    "Washington Post, ProPublica, The Publics Radio and Rhode Island PBS, "
    "and The Brown Daily Herald to discuss the evolving landscape of "
    "immigration reporting in 2025. Panelists will reflect on the key "
    "migration issues they are covering today, how reporting priorities and "
    "narratives have shifted over the past several years, and the challenges "
    "of covering immigrant communities with accuracy and care. They will also "
    "share stories that have had a lasting impact on them and their "
    "audiences.The event will conclude with an open Q&A, offering students "
    "and community members an opportunity to explore the role of journalism "
    "in shaping public understanding of immigration. About the panelists: "
    "Arelis Hernandez is a Texas-based national reporter covering immigration "
    "and the border for The Washington Post. Since 2019, she has led the "
    "paper’s border coverage from the erection of Trump border wall to the "
    "shutting down of the border in the pandemic, the impact of migration on "
    "the borderlands and Biden administration policy evolution that saw tens "
    "of thousands of people seek entry into the U.S. from Mexico. Immigration "
    "has always been an undercurrent her career but prior to moving to Texas, "
    "Hernandez covered national breaking news, was part of investigative "
    "teams recognized for their work and spent brief periods reporting in "
    "Puerto Rico and Venezuela. She’s been with the Post since 2014. Melissa "
    "Sanchez joined ProPublica in 2017 and is based in Chicago, where she "
    "writes about immigrants and labor. She has reported on conditions at "
    "shelters for unaccompanied immigrant children, the state of Illinois’ "
    "failure to adequately serve immigrant families caught up in the state’s "
    "child welfare system, and the growing number of Central American "
    "teenagers working in suburban factories. In 2023, she and her colleague, "
    "Maryam Jameel, reported on conditions for immigrant workers on Wisconsin "
    "dairy farms; that reporting prompted a federal civil rights "
    "investigation and led to the creation of an $8 million fund to build "
    "housing for farmworkers. The series was a finalist for an Anthony Shadid "
    "Award for Journalism Ethics. Their reporting on how a small Wisconsin "
    "city was grappling with the sudden arrival of hundreds of Nicaraguan "
    "families, in collaboration with WBUR’s On Point, won a national Murrow "
    "award. This year, Melissa has worked with colleagues and a group of "
    "independent reporters from Venezuela to examine the deportation of more "
    "than 230 Venezuelan men to a maximum security prison in El Salvador – "
    "where they later said they were tortured. The reporting showed that, "
    "despite calling them “the worst of the worst,” the Trump administration "
    "knew that the vast majority of the men had never been convicted of a "
    "violent crime in the U.S. The investigation also showed how, by and "
    "large, the men were in the U.S. immigration system, not absconding from "
    "authorities. The reporters also published a first-of-its-kind "
    "interactive database with profiles on 238 of the men. Melissa previously "
    "worked for The Chicago Reporter, Catalyst Chicago, El Nuevo Herald in "
    "Miami and the Yakima Herald-Republic in Washington. She is the daughter "
    "of immigrants from Mexico and El Salvador and speaks Spanish fluently. "
    "Luis Hernandez is a thirty-year veteran of broadcast journalism, "
    "with more than twenty of those years in public media. In that time he "
    "has covered a gamut of topics like politics, the environment, "
    "the economy, and the arts. He’s hosted shows and anchored news in "
    "markets like Las Vegas, Miami, and Providence, and won numerous awards "
    "including Florida anchor of the year, and a regional Edward R. Murrow "
    "award. He’s also the host of the podcasts Planet Earth 2072 - a climate "
    "podcast. and The Reporter’s Studio - a podcast about the media. Sophia "
    "Wotman is a senior at Brown University studying Political Science. She "
    "is a University News Editor for The Brown Daily Herald, covering the "
    "Activism and Affinity and Identity beats. In her reporting, Sophia has "
    "covered a range of on- and off-campus organizing, on topics including "
    "environmental justice, immigration, housing equity, affirmative action, "
    "and the conflict in Israel and Gaza. With the implications of the Trump "
    "administration’s DEI and identity-based policies largely still unknown, "
    "she has been interviewing students, University leaders, and affinity "
    "centers to investigate how these policy changes will impact Brown. "
    "Earlier this year, she covered the administration’s revocation of "
    "student visas at Brown, and the subsequent reactivation of their visa "
    "registration records. Sophia has taken her reporting experience into her "
    "work in political communications, and worked as a press intern for "
    "Senator Sheldon Whitehouse (D-RI) this past summer. She is particularly "
    "interested in women’s rights and civil rights issues, and is writing a "
    "senior thesis on abortion access throughout the United States. After "
    "graduating from Brown, she hopes to pursue work related to both press "
    "and civil rights issues, through communications work or policy research. "
    "Sophia is also a jazz trumpeter and enjoys performing in the Brown Jazz "
    "Band and pep band.  ",
)

print(response.text)
# print(response.text.split(","))
